// Generated by CoffeeScript 1.4.0
(function() {

  if (Meteor.isClient) {
    Meteor.BrowserMsg.listen({
      shout: function(say) {
        return alert(say);
      }
    });
    Template.hello.events({
      'click #shout': function() {
        return Meteor.BrowserMsg.send('shout', $('#say').val());
      }
    });
  }

}).call(this);
