// Generated by CoffeeScript 1.4.0
(function() {
  var localStorage_message_key,
    __slice = [].slice;

  localStorage_message_key = 'Meteor.LocalMsg.msg';

  Meteor.LocalMsg = {
    _listeners: {},
    listen: function(callbacks) {
      var callback, name;
      for (name in callbacks) {
        callback = callbacks[name];
        this._listeners[name] = callback;
      }
      return void 0;
    },
    send: function() {
      var arg, name, r, v;
      name = arguments[0], arg = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      r = Math.random().toString().substr(2);
      v = JSON.stringify([name].concat(__slice.call(arg)));
      localStorage.setItem(localStorage_message_key, r + ':' + v);
      return void 0;
    }
  };

  window.addEventListener('storage', (function(event) {
    var arg, name, val, _base, _ref;
    if (event.key === localStorage_message_key) {
      val = event.newValue;
      _ref = JSON.parse(val.substr(val.indexOf(':') + 1)), name = _ref[0], arg = 2 <= _ref.length ? __slice.call(_ref, 1) : [];
      if (typeof (_base = Meteor.LocalMsg._listeners)[name] === "function") {
        _base[name].apply(_base, arg);
      }
      return void 0;
    }
  }), false);

}).call(this);
