// Generated by CoffeeScript 1.4.0
(function() {

  Template.main.delay = function() {
    return Session.get('delay');
  };

  Meteor.BrowserMsg.listen({
    'a_message': function(time) {
      return Session.set('delay', (new Date().getTime() - time) + 'ms');
    }
  });

  Template.main.events({
    'click #send': function() {
      return Meteor.BrowserMsg.send('a_message', new Date().getTime());
    }
  });

}).call(this);
