// Generated by CoffeeScript 1.4.0
(function() {
  var sentAt;

  sentAt = null;

  Meteor.methods({
    sendingMessageAt: function(time) {
      return sentAt = time;
    },
    receivedMessageAt: function(time) {
      return console.log('message delay', (time - sentAt) + "ms");
    }
  });

}).call(this);
